### ISSUE TITLE
Automatizar geração da documentação Doxygen

### ISSUE THREAD

**Issue by piklprado** [piLaboratory/TWoLife#5]
No momento temos que usar uma maracutaia e gerar a documentação Doxygen manualmente (https://github.com/piLaboratory/TWoLife/wiki/Documenta%C3%A7%C3%A3o-Doxygen).

Será que podemos automatizar a geração da documentação, com Chalom havia feito no servidor svn da LAGE?

**Comment by renatocoutinho** [comment]
Por favor dêem uma olhada na minha sugestão de usar hooks do git aqui: instruções atualizadas na wiki (https://github.com/piLaboratory/TWoLife/wiki/Documenta%C3%A7%C3%A3o-Doxygen). Claro que cada usuário tem que configurar, mas tendo alguns commiters "frequentes" com isso configurado já deve resolver.

**Comment by andrechalom** [comment]
Ops, li errado no PR, acho que seu PR pode fechar esse issue sim

**Comment by piklprado** [comment]
Genial! Tb acho que pode fechar sim

**Comment by renatocoutinho** [comment]
Beleza, depois vejam se funciona pra vocês também hahah
